name: Create Release
on:
  push:
    # 여기에 branches를 넣으면 or 조건으로 동작함
    # tags 로만 트리거 되는 동작은 github.ref 가 refs/tags/{tag-name} 이고,
    # checkout 을 하면 detached HEAD 상태로 동작
        # fetch-depth: 0 을 꼭 넣어줘야 함. 아니면 해당 커밋만 가져옴.
        # 브랜치 정보를 가져올 수 없어서 main 여부 체크를 할 수 없음.
    tags:
      - 'trigger*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          ref: 'main'
#        with:
#          fetch-depth: 0

      - name: git status
        run: |
          git status
          git log --oneline

      - name: get current branch
        id: get_branch
        run: git branch --show-current

      # tag format: trigger-ecs|worker-{timestamp}-{username}
      - name: Get triggered tag
        id: trigger_tag
        run: |
          echo ::set-output name=tag::$(git describe --tags --abbrev=0 | grep trigger)
      - name: Set new info
        id: new
        run: |
          echo ::set-output name=commit::$(git show-ref -s ${{ steps.trigger_tag.outputs.tag }})
          echo ::set-output name=username::$(echo ${{ steps.trigger_tag.outputs.tag }} | cut -d'-' -f6)
          echo ::set-output name=tag::$(echo ${{ steps.trigger_tag.outputs.tag }} | cut -d'-' -f2-5)

      - name: Get latest release
        id: latest_release
        run: |
          echo ::set-output name=tag::$(git tag --sort=-creatordate | grep -v trigger | sed -n 1p)
          echo ::set-output name=commit::$(git show-ref -s $(git tag --sort=-creatordate | grep -v trigger | sed -n 1p))

      - name: Get changelog
        id: changelog
        run: |
          echo ::set-output name=changelog::$(git log --pretty=format:"[%h](https://github.com/mediquitous-dev/zelda/commit/%h) - <b>%s</b> : @%an </br>" ${{ steps.latest_release.outputs.commit }}..${{ steps.new.outputs.commit }})

      - name: Create a release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.new.outputs.tag }}
          name: Release ${{ steps.new.outputs.tag }}
          makeLatest: true
          generateReleaseNotes: false
          body: >
            [Compare link](https://github.com/mediquitous-dev/zelda/compare/${{ steps.latest_release.outputs.tag }}...${{ steps.new.outputs.tag }})
            <br/>
            <br/>
            ${{ steps.changelog.outputs.changelog }}
            <br/>
            deploy by @${{ steps.new.outputs.username }}
