name: Deploy Log
on:
  push:
    # 여기에 branches를 넣으면 or 조건으로 동작함
    # tags 로만 트리거 되는 동작은 github.ref 가 refs/tags/{tag-name} 이고,
    # checkout 을 하면 detached HEAD 상태로 동작
    # 또한, 태그 ref를 가져오기 위해 fetch-depth: 0 을 꼭 해줘야 함. 아니면 해당 커밋만 가져옴.
    # 브랜치 정보를 가져올 수 없어서 main 여부 체크를 할 수 없음.
    tags:
      - 'trigger*'

jobs:
  deploy-log:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v1
        with:
          fetch-depth: 0

      - name: Get tag annotation
        id: tag
        run: |
          if [ -z "${PROVIDED_TAG}" ]; then
            TAG_ANNOTATION=$(git for-each-ref "${GITHUB_REF}" --format '%(contents)')
          else
            TAG_ANNOTATION=$(git for-each-ref "refs/tags/${PROVIDED_TAG}" --format '%(contents)')
          fi
          echo "$TAG_ANNOTATION"
          echo "::set-output name=annotation::$TAG_ANNOTATION"

      # tag format: trigger-v2023-06-01-0915
      - name: Get triggered tag
        id: trigger_tag
        run: |
          echo ::set-output name=tag::$(git describe --tags --abbrev=0 | grep trigger)
      - name: Set new info
        id: new
        run: |
          echo ::set-output name=commit::$(git show-ref -s ${{ steps.trigger_tag.outputs.tag }})
          echo ::set-output name=tag::$(echo ${{ steps.trigger_tag.outputs.tag }} | cut -d'-' -f2-5)
          new_commit_time=$(git show -s --format=%cd --date=iso-strict ${{ steps.trigger_tag.outputs.tag }} | tail -n 1)
          echo ::set-output name=commit_time::$(TZ="Asia/Seoul" date -d "$new_commit_time +1 second" --iso-8601=seconds)
          

      # {A_commit_time}..{B_commit_time} 을 하면 A_comit_time 포함이기 때문에, 1초를 더해준다.
      - name: Get latest deploy log
        id: latest_log
        run: |
          echo ::set-output name=tag::$(git tag --sort=-creatordate | grep -v trigger | sed -n 1p)
          echo ::set-output name=commit::$(git show-ref -s $(git tag --sort=-creatordate | grep -v trigger | sed -n 1p))
          echo ::set-output name=commit_time::$(TZ="Asia/Seoul" date -d "$(git show -s --format=%cd --date=iso-strict $(git tag --sort=-creatordate | grep -v trigger | sed -n 1p)) +1 second" --iso-8601=seconds)

      - name: List merged PRs
        id: pr_list
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pr_list=$(gh pr list --search "is:merged merged:${{ steps.latest_log.outputs.commit_time }}..${{ steps.new.outputs.commit_time }}" | awk -F '\t' '{print "#" $1, $2}')
          pr_list="${pr_list//$'\n'/'%0A'}"  
          echo "::set-output name=pr_list::$pr_list"

      - name: Get changelog
        id: changelog
        run: |
          echo ::set-output name=changelog::$(git log --pretty=format:"[%h](https://github.com/mediquitous-dev/zelda/commit/%h) - %s</br>" ${{ steps.latest_log.outputs.commit }}..${{ steps.new.outputs.commit }})

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.new.outputs.tag }}
          name: Release ${{ steps.new.outputs.tag }}
          makeLatest: true
          body: >
            [Compare link](https://github.com/mediquitous-dev/zelda/compare/${{ steps.latest_log.outputs.tag }}...${{ steps.new.outputs.tag }})
            <br/>
            <br/>
            <b>PR LIST</b>
            <br/>
            ${{ steps.pr_list.outputs.pr_list }}
            <br/>
            <br/>
            <br/>
            <b>CHANGELOG</b>
            <br/>
            ${{ steps.changelog.outputs.changelog }}
            <br/>
            deployed by @${{ github.actor }}

      - name: slack body
        id: slack_body
        run: |
          annotation="${{ steps.tag.outputs.annotation }}"
          tag="${{ steps.new.outputs.tag }}"
          release_url="https://github.com/mediquitous-dev/zelda/releases/tag/${tag}"
          pr_list=$(echo "${{ steps.pr_list.outputs.pr_list }}" | head -n 2 | awk -F '\t' '{print $0}')
          pr_list="${pr_list//$'\n'/'%0A'}"  
          log=$(git log --pretty=format:'%h - %s' | head -n 3 | awk -F '\t' '{print $0}')
          log="${log//$'\n'/'%0A'}"
          body=""
          if [[ -n "$annotation" && $annotation != Merge* ]]; then
            body+="*<${release_url}|${tag}>: ${annotation}*%0A%0A"
          else
            body+="*<${release_url}|${tag}>*%0A%0A"
          fi
          if [ -n "$pr_list" ]; then
            body+="${pr_list}%0A%0A"
          fi
          if [ -n "$log" ]; then
            body+="${log}%0A%0A"
          fi
          echo "::set-output name=body::$body"

#      - name: Notify Slack
#        uses: rtCamp/action-slack-notify@v2
#        env:
#          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
#          SLACK_CHANNEL: 'nugu_renewal'
#          SLACK_MESSAGE: ${{ steps.slack_body.outputs.body }}
#          SLACK_USERNAME: 'deploy-bot'
#          SLACK_ICON: 'https://image.lexica.art/full_jpg/340b0fc2-c10a-471b-84f8-271d252b7704'
#          SLACK_TITLE: 'www.nugu.jp 에 배포가 시작되었습니다. 약 7분 후에 완료됩니다.'
#          SLACK_FOOTER: ''
#          MSG_MINIMAL: true
