name: Create Release
on:
  push:
    # 여기에 branches를 넣으면 or 조건으로 동작함
    # tags 로만 트리거 되는 동작은 github.ref 가 refs/tags/{tag-name} 이고,
    # checkout 을 하면 detached HEAD 상태로 동작함 > fetch-depth: 0 을 꼭 넣어줘야 함. 아니면 해당 커밋만 가져옴.
    tags:
      - 'trigger*'

jobs:
  release:
#    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: git status
        run: |
          git status
          git log

      # tag format: trigger-ecs|worker-{timestamp}-{username}
      - name: Get triggered tag
        id: trigger_tag
        run: |
          echo ::set-output name=tag::$(git describe --tags --abbrev=0 | grep trigger)

      - name: Set new info
        id: new
        run: |
          echo ::set-output name=username::$(echo ${{ steps.trigger_tag.outputs.tag }} | cut -d'-' -f4)
          echo ::set-output name=tag::$(echo ${{ steps.trigger_tag.outputs.tag }} | cut -d'-' -f2-3)

      - name: Get latest release
        id: latest_release
        run: |
          echo ::set-output name=tag::$(git tag --sort=-creatordate | grep -v trigger | sed -n 1p)

      - name: print
        run: |
          echo ${{ steps.latest_release.outputs.tag }}
          echo ${{ steps.new.outputs.tag }}

#      - name: print the result
#        run: |
##          echo ${{ steps.latest_release.outputs.commit }}
#          echo ${{ steps.latest_release.outputs.tag }}
#
#      - name: Get changelog
#        id: changelog
#        run: |
#          git log --pretty=format:"%h - %s : @%an" ${{ steps.latest_release.outputs.tag }}..${{ steps.new.outputs.tag }}
#
##            echo ::set-output name=changelog::$(git log --pretty=format:"[%h](https://github.com/hslim8888/test-action/commit/%h) - %s : @%an" ${{ steps.latest_release.outputs.commit }}..${{ steps.new.outputs.commit }})
#
##      - name: Create a release
##        uses: ncipollo/release-action@v1
##        with:
##          tag: ${{ steps.new.outputs.tag }}
##          name: Release ${{ steps.new.outputs.tag }}
##          makeLatest: true
##          body: >
##            [Compare link](https://github.com/hslim8888/test-action/compare/${{ steps.latest_release.outputs.tag }}...${{ steps.new.outputs.tag }})
##            ${{ steps.changelog.outputs.changelog }}
##            deploy by @${{ steps.new.outputs.username }}
#
